### ISSUE TITLE
(Priority 1) attach input handlers to the words so they can register touch events

### ISSUE THREAD

**Issue by lpmi-13** [lpmi-13/sentencefactory#3]
enable touch events on the words themselves to be registered. The current idea on this is to split the sentence into an array and use the "word.inputEnabled = true" and "word.events.onInputDown.add(foo, this)" Phaser handlers for the part of the array with the feature.

In terms of maintaining the (approximately) correct spacing between words, the current idea is to use the width of the word as a variable and sent the following word out across the screen when the first word's width is at a given offset from the right side of the screen.

psuedocode example:

var wordWidth = word.width;
var gameWdith = game.width;
//in Phaser, the 'x' of an object is at the upper left-hand corner of the sprite on the screen
if ((word.x + wordWidth) <= game.width - 10) {
    callFunctionToSendOutNextWord();
}

**Comment by richdouglasevans** [comment]
I plan to work on this once #18 and #19 are merged.

**Comment by richdouglasevans** [comment]
Mmm. It seems like in order to do this each word has to be a sprite.

I shall have a think :thinking:

**Comment by lpmi-13** [comment]
yeah, I think I agree that each word (in order to have their own event handler) needs to be an object...and I know I've done this with adding "text" instead of "sprite", but it should be conceptually the same thing, I think.

It looks like there is a "full length" property of the entire scrolling sentence, so we might be able to calculate where to attach a handler based on the font size...but this seems extremely messy and overly architectured. I think just splitting each sentence into separate text objects/sprites/bananas is the way to go.
